### PR TITLE
Change default of keyCombinationsOnly to false

### PR DESCRIPTION
**Pull request by karlhorky**
Hi @karaggeorge,

First of all, thanks for this awesome plugin! Really nice to have this built in to Kap!

This pull request changes the default of `keyCombinationsOnly` to `false`. I would suggest this as the default because of my experience when installing the plugin, which I can imagine could happen to others too:

A. I installed the plugin and tried it out quickly on a GitHub page
B. I tried keyboard combinations and everything was great
C. I tried a single shortcut key <kbd>e</kbd>, and nothing showed up

This led me to believe that the plugin did not support this, which led me to search through the GitHub repos for any open issues (in case others also have wanted this).

I then found the configuration option.

---

So what I would suggest is that the plugin should by default capture all keys, and then if users want to capture something that would require typing (which could be super annoying with all keys showing), they could configure this.

However, to play devil's advocate, I can understand if the use case of capturing typing is considered too primary for your customers, which would be a reason not to accept this PR.

What are your thoughts?

### CODE REVIEW

**Comment by karaggeorge** [comment]
I like the idea. Yeah my original thought was that people would mostly only want to show combinations and not like *every* key pressed. But I see how showing everything it can do and then having options to dial it down might be a better way. I wonder if there's a better way we can show what plugins can do when you install them. I does pop up a notification that says you can configure it when you first install it, but I guess most people just want to try it out first out of the box.

I'll merge/release this tomorrow

**Comment by karlhorky** [comment]
Thanks for your consideration :)

> I wonder if there's a better way we can show what plugins can do when you install them

Yeah, that would be great!

Maybe allow plugins to specify an "install guide" that shows after installation? This could be one or a combination of the following:

1. A formatted text description (Markdown? HTML?)
2. Images with caption text
3. Video (mp4? gif?)

cc @sindresorhus

**Comment by karaggeorge** [comment]
@karlhorky this was released. Thank you!

**Comment by karlhorky** [comment]
Thanks! Glad to help :)

**Pull request merged**
